### ISSUE TITLE
Don't know how to play the brisca

### ISSUE THREAD

**Issue by Vaelic0** [MiixZ/PTC_sesiones#1]
Learn to play  brisca!

**Comment by MiixZ** [comment]
Thanks for your request! I would like to learn barisca, but now im going to try brisca too!

**Comment by Vaelic0** [comment]
Won't fix, I don't know how to play brisca

**Comment by MiixZ** [comment]
Oh, I see. Did you consider finding some information about "women"? Maybe it would help u.
